namespace: default
resources:
  - ../default
  - ccm-resource-set.yaml

patchesStrategicMerge:
  - patches/external-cloud-provider.yaml

configMapGenerator:
  - name: cloud-controller-manager-addon
    files:
      - cloud-controller-manager.yaml
  - name: cloud-node-manager-addon
    files:
      - cloud-node-manager.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
