namespace: default
resources:
  - ../base
  - ../default/machine-deployment.yaml
patchesStrategicMerge:
  - patches/private-lb.yaml
  - patches/apiserver-host-dns.yaml
  - patches/azure-bastion.yaml

