apiVersion: v1
kind: Secret
metadata:
  name: ${AZURE_CLUSTER_IDENTITY_SECRET_NAME}
  annotations:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
type: Opaque
data:
  clientSecret: ${AZURE_CLIENT_SECRET_B64}
